-- AlterTable
ALTER TABLE `stores` ADD COLUMN `city` VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN `pincode` VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN `shopNo` VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN `shopType` VARCHAR(100) NOT NULL DEFAULT 'Kirana',
    ADD COLUMN `state` VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN `village` VARCHAR(100) NULL;
